### PR TITLE
Switch license to AGPL

### PR DESCRIPTION
**Pull request by kfogel**
As per discussion with Permanent earlier today.

### CODE REVIEW

**Comment by kfogel** [comment]
@cecilia-donnelly Over to you for review.

**Comment by cecilia-donnelly** [comment]
To give a little more detail: Permanent's default license is the AGPL and we would like this newly-transferred repository to follow that convention.

**Review by cecilia-donnelly — APPROVED** [review]

**Comment by kfogel** [comment]
Thanks, @cecilia-donnelly!  I think you have to do the merge (oddly, I had the right to *create* this repository, but apparently I don't have rights to merge approved changes into it from PRs).

**Comment by kfogel** [comment]
Thanks, @cecilia-donnelly.

**Pull request merged**
